src/lib/cls.service.ts
src/types/recursive-key-of.type.ts

I've made this change on `@nestjs/config`: https://github.com/nestjs/config/pull/907 I found that it closes #46 as well

fix: add `AbortController` to the terminal types list

---

.github/workflows/run-tests.workflow.yml
README.md
test/gql/gql-apollo.spec.ts
test/gql/gql-mercurius.spec.ts

Context setup for GQL no longer requires `useEnterWith`

docs: update docs and tests for gql

---

README.md
src/lib/cls-initializers/cls.middleware.ts
src/lib/cls.options.ts

use case is initializing iron-session ([vvo/iron-session](https://github.com/vvo/iron-session)) and adding the session object or just specific session data to continuation-local storage. Iron-session requires the response object to initialize and fails without it (even though it's not really needed until you call session.save() or session.destroy(). see https://github.com/vvo/iron-session/blob/70d2ff14aacb51e83284d51832fdcda539b4dabc/src/core.ts#L107)
An example implementation could look like this:
```typescript
ClsModule.forRoot({
middleware: {
mount: true,
setup: (cls, req: Request, res:Response) => {
const session = await getIronSession(req, res, {
cookieName: "myapp_cookiename",
password: "complex_password_at_least_32_characters_long",
// secure: true should be used in production …
```

Add res to middleware setup

---

README.md

Fix a typo `ClsModule.rotRoot()` -> `ClsModule.forRoot()`

fix: fix typo in readme

---

docs/docs/03_features-and-use-cases/06_proxy-providers.md
docs/docs/04_api/02_module-options.md
packages/core/src/lib/proxy-provider/proxy-provider-manager.ts
packages/core/src/lib/proxy-provider/proxy-provider.interfaces.ts
packages/core/test/proxy-providers/for-feature.spec.ts

BREAKING CHANGE: Proxied object now has `object` type by default. Proxies of `function` types must be explicitly enabled by using `type: 'function'` in the `forFeature` registration.
Closes #82

fix: explicitly enable function proxy providers

---

docs/docs/04_api/01_service-interface.md
packages/core/src/lib/cls.service.spec.ts
packages/core/src/lib/cls.service.ts

BREAKING CHANGE: The default of the `ifNested` option was changed from `override` to to `inherit`.
The reason is that users rarely need to use a clean context in the middle of the application if it already contains important details. The more common scenario is to change a part of the context in some section of the code while keeping all other values intact.

chore: change default of nested cls option

---

docs/docs/03_features-and-use-cases/06_proxy-providers.md
packages/core/src/lib/cls-initializers/use-cls.decorator.ts
packages/core/src/lib/cls.options.ts
packages/core/src/lib/cls.service.ts

Closes #85 
BREAKING CHANGE: The default option for `resolveProxyProviders` was on the `@UseCls` decorator was changed from `false` to `true`

feat: expose cls.run options on decorator, update defaults

---

docs/docs/06_plugins/01_available-plugins/01-transactional/index.md
packages/transactional/src/index.ts
packages/transactional/src/lib/propagation.ts
packages/transactional/src/lib/transaction-host.ts
packages/transactional/src/lib/transactional.decorator.ts
packages/transactional/test/propagation.spec.ts
packages/transactional/test/transactional.spec.ts

Closes #108 
BREAKING CHANGE: The default mode is now `REQUIRED` which re-uses the transaction if one exists, while previously a new one was always started.

feat: add support for transaction propagation modes

---

packages/core/src/lib/cls.service.spec.ts
packages/core/src/lib/cls.service.ts

* When accessing symbol keys without context, an error is no longer thrown.
* When creating ClsService without passing als, an error is thrown immediately.

fix: symbol key access and explicit constructor error

---

docs/docs/06_plugins/01_available-plugins/01-transactional/03-pg-promise-adapter.md
docs/docs/06_plugins/01_available-plugins/01-transactional/index.md
packages/transactional-adapters/transactional-adapter-pg-promise/README.md
packages/transactional-adapters/transactional-adapter-pg-promise/jest.config.js
packages/transactional-adapters/transactional-adapter-pg-promise/package.json
packages/transactional-adapters/transactional-adapter-pg-promise/src/index.ts
packages/transactional-adapters/transactional-adapter-pg-promise/src/lib/transactional-adapter-pg-promise.ts
packages/transactional-adapters/transactional-adapter-pg-promise/test/docker-compose.yml
packages/transactional-adapters/transactional-adapter-pg-promise/test/transactional-adapter-pg-promise.spec.ts
packages/transactional-adapters/transactional-adapter-pg-promise/tsconfig.json
tsconfig.json
yarn.lock

@nestjs-cls/transactional adapter for [pg-promise](https://github.com/vitaly-t/pg-promise).
Two caveats:
- `pg-promise` is Postgres-specific, so the tests require `docker-compose`.
- For now, the options are typed with `any`.
Apart from these 2 points, my adapter is the same as the those for Knex and Prisma.

feat: add @nestjs-cls/transactional-adapter-pg-promise

---

packages/core/src/lib/cls-initializers/use-cls.decorator.spec.ts
packages/core/src/lib/cls.service.ts

Methods decorated with `@UseCls()` (without `runOptions`) are not called when running inside a parent context.
This PR prepends the default options to the options passed down to the `cls.run(options, callback)` function. This way, `options.ifNested` is always defined (default to `inherit`), and the callback is always triggered in the `switch (options.ifNested) ... case` block.
Since `@UseCls()` calls `run` with an empty options object: `cls.run({}, callback)` ; it fixes the issue 👍

fix(core): handle nested context correctly with UseCls decorator

---

docs/docs/06_plugins/01_available-plugins/01-transactional/index.md
packages/core/src/lib/proxy-provider/proxy-provider-manager.ts
packages/transactional-adapters/transactional-adapter-knex/test/transactional-adapter-knex.spec.ts
packages/transactional-adapters/transactional-adapter-kysely/test/transactional-adapter-kysely.spec.ts
packages/transactional-adapters/transactional-adapter-pg-promise/test/transactional-adapter-pg-promise.spec.ts
packages/transactional-adapters/transactional-adapter-prisma/test/transactional-adapter-prisma.spec.ts
packages/transactional/src/index.ts
packages/transactional/src/lib/inject-transaction.decorator.ts
packages/transactional/src/lib/interfaces.ts
packages/transactional/src/lib/plugin-transactional.ts
packages/transactional/src/lib/symbols.ts
packages/transactional/src/lib/transaction-host.ts
packages/transactional/test/inject-transaction.spec.ts
packages/transactional/test/transaction-adapter-mock.ts

Adds the option to use `@InjectTransaction` to inject a Proxy of the transaction instance instead of the `TransactionHost`.

feat: add option to inject tx directly as Proxy

---

docs/docs/06_plugins/01_available-plugins/01-transactional/04-pg-promise-adapter.md
packages/transactional-adapters/transactional-adapter-pg-promise/src/lib/transactional-adapter-pg-promise.ts
packages/transactional-adapters/transactional-adapter-pg-promise/test/transactional-adapter-pg-promise.spec.ts

This PR adds the ability to specify default options for the `@Transactional` decorator, so that they don't need to be specified repeatedly.

PgPromise adapter: add default tx options

---

docs/docs/06_plugins/01_available-plugins/01-transactional/10-creating-custom-adapter.md
packages/transactional-adapters/transactional-adapter-knex/src/lib/transactional-adapter-knex.ts
packages/transactional-adapters/transactional-adapter-knex/test/transactional-adapter-knex.spec.ts
packages/transactional-adapters/transactional-adapter-kysely/src/lib/transactional-adapter-kysely.ts
packages/transactional-adapters/transactional-adapter-kysely/test/transactional-adapter-kysely.spec.ts
packages/transactional-adapters/transactional-adapter-pg-promise/src/lib/transactional-adapter-pg-promise.ts
packages/transactional-adapters/transactional-adapter-pg-promise/test/transactional-adapter-pg-promise.spec.ts
packages/transactional-adapters/transactional-adapter-prisma/src/lib/transactional-adapter-prisma.ts
packages/transactional-adapters/transactional-adapter-prisma/test/transactional-adapter-prisma-custom-client.spec.ts
packages/transactional-adapters/transactional-adapter-prisma/test/transactional-adapter-prisma.spec.ts
packages/transactional-adapters/transactional-adapter-typeorm/src/lib/transactional-adapter-typeorm.ts
packages/transactional-adapters/transactional-adapter-typeorm/test/transactional-adapter-typeorm.spec.ts
packages/transactional/src/lib/interfaces.ts
packages/transactional/src/lib/plugin-transactional.ts
packages/transactional/src/lib/transaction-host.ts
packages/transactional/test/default-options.spec.ts
packages/transactional/test/multiple-connections.spec.ts
packages/transactional/test/named-connection.spec.ts
packages/transactional/test/transaction-adapter-mock.ts

Enables setting default options for all transactions started with `@nestjs-cls/transactional`

feat(transactional): add default options parameter to transactional adapter 

---

docs/docs/06_plugins/01_available-plugins/01-transactional/index.md
packages/transactional/src/lib/interfaces.ts
packages/transactional/src/lib/plugin-transactional.ts
packages/transactional/test/inject-transaction.spec.ts

This is needed specifically for a future `mongodb` and `mongoose` support, because the lack of an active transaction is denoted by passing `null` or `undefined` as the `session` value.
But proxying those values (or any primitive values for that matter) is not supported by JavaScript.

feat(transactional): enable adapters to opt out of transactional proxy support

---

docs/docs/06_plugins/01_available-plugins/01-transactional/07-mongoose-adapter.md
packages/transactional-adapters/transactional-adapter-mongoose/README.md
packages/transactional-adapters/transactional-adapter-mongoose/jest.config.js
packages/transactional-adapters/transactional-adapter-mongoose/package.json
packages/transactional-adapters/transactional-adapter-mongoose/src/index.ts
packages/transactional-adapters/transactional-adapter-mongoose/src/lib/transactional-adapter-mongoose.ts
packages/transactional-adapters/transactional-adapter-mongoose/test/transactional-adapter-mongoose.spec.ts
packages/transactional-adapters/transactional-adapter-mongoose/tsconfig.json
tsconfig.json
yarn.lock

feat(transactional-adapter-mongoose): add `mongoose` adapter

---

docs/docs/05_considerations/02_compatibility.md
docs/docusaurus.config.js
packages/core/package.json
packages/core/src/lib/cls-initializers/utils/context-cls-store-map.ts
packages/core/test/websockets/expect-ids-websockets.ts
packages/core/test/websockets/test-ws.filter.ts
packages/core/test/websockets/websockets.app.ts
packages/core/test/websockets/ws.spec.ts
yarn.lock

fix(core): support primitive values in websocket payload

---

docs/docs/06_plugins/index.md
packages/core/src/lib/cls.module.ts
packages/core/test/plugin/plugin.spec.ts

Enables injection of plugins from external modules for library development.
https://github.com/Papooch/nestjs-cls/discussions/191

feat(core): adds ClsModule.registerPlugins([new Plugin()])

---

packages/transactional/src/lib/transaction-host.ts
packages/transactional/test/edge-cases/nested-non-awaited-transaction.spec.ts
packages/transactional/test/transaction-adapter-mock.ts

fix(transactional): do not reuse parent transaction context

---

packages/core/src/lib/cls.module.ts

When using NestJS 11 with `setGlobalPrefix('api')`, the following warning appears:
```
WARN [LegacyRouteConverter] Unsupported route path: "/api/(.*)". In previous versions, the symbols ?, *, and + were used to denote optional or repeating path parameters. The latest version of "path-to-regexp" now requires the use of named parameters. For example, instead of using a route like /users/* to capture all routes starting with "/users", you should use /users/*path. For more details, refer to the migration guide. Attempting to auto-convert...
```
This warning occurs because `ClsModule` uses the legacy route pattern `(.*)` for FastifyAdapter, which is no longer supported by newer versions of `path-to-regexp` used in Express>=v5 and `@fastify/middie>=v9`.
Looking at the [NestJS core …

fix(core): update fastify route pattern to support latest syntax

---

packages/core/src/lib/proxy-provider/proxy-provider-manager.ts

fix(core): allow all Object.prototype keys access on strict providers

---

packages/core/src/lib/cls-initializers/utils/context-cls-store-map.ts
packages/core/test/common/test.middleware.ts
packages/core/test/rest/expect-ids-rest.ts
packages/core/test/rest/http-express.spec.ts
packages/core/test/rest/http-fastify.spec.ts
packages/core/test/rest/http.app.ts

fix(core): reuse context when other Cls-enhancers are used together with ClsMiddleware with Fastify 5

---

packages/transactional-adapters/transactional-adapter-kysely/package.json
packages/transactional-adapters/transactional-adapter-kysely/src/lib/transactional-adapter-kysely.ts
packages/transactional-adapters/transactional-adapter-kysely/test/transactional-adapter-kysely.spec.ts
yarn.lock

Kysely has support for transaction access modes now ([0.28.0](https://github.com/kysely-org/kysely/releases/tag/0.28.0)) so I've ported it here.
Might be a good idea to bump to 0.28.2 as well to benefit from the latest bug fixes.
Cheers 🙂

feat(transactional-adapter-kysely) support kysely access mode

---

packages/core/package.json

Fixes #239 
Previously, a `build:release` script was added to the root package json in https://github.com/Papooch/nestjs-cls/pull/306 that should address the issue, but a rogue `&& yarn build` was still left in the `prepublish` script of the core package, which would add the source maps back.
This PR removes that unnecessary  build step from the core package (all other packages have already been published without source maps)

fix(core): do not publish source maps

---

docs/docs/06_plugins/01_available-plugins/01-transactional/01-prisma-adapter.md
docs/docs/06_plugins/01_available-plugins/01-transactional/06-mongodb-adapter.md
docs/docs/06_plugins/01_available-plugins/01-transactional/07-mongoose-adapter.md
docs/docs/06_plugins/01_available-plugins/01-transactional/99-creating-custom-adapter.md
docs/docs/06_plugins/01_available-plugins/01-transactional/index.md
packages/transactional-adapters/transactional-adapter-drizzle-orm/src/lib/transactional-adapter-drizzle-orm.ts
packages/transactional-adapters/transactional-adapter-drizzle-orm/test/transactional-adapter-drizzle-orm.spec.ts
packages/transactional-adapters/transactional-adapter-knex/src/lib/transactional-adapter-knex.ts
packages/transactional-adapters/transactional-adapter-knex/test/transactional-adapter-knex.spec.ts
packages/transactional-adapters/transactional-adapter-kysely/src/lib/transactional-adapter-kysely.ts
packages/transactional-adapters/transactional-adapter-kysely/test/transactional-adapter-kysely.spec.ts
packages/transactional-adapters/transactional-adapter-pg-promise/src/lib/transactional-adapter-pg-promise.ts
packages/transactional-adapters/transactional-adapter-pg-promise/test/transactional-adapter-pg-promise.spec.ts
packages/transactional-adapters/transactional-adapter-prisma/prisma/migrations/20240119144105_init/migration.sql
packages/transactional-adapters/transactional-adapter-prisma/prisma/schema.prisma
packages/transactional-adapters/transactional-adapter-prisma/src/lib/savepoint-syntax.ts
packages/transactional-adapters/transactional-adapter-prisma/src/lib/transactional-adapter-prisma.ts
packages/transactional-adapters/transactional-adapter-prisma/test/transactional-adapter-prisma.spec.ts
packages/transactional-adapters/transactional-adapter-typeorm/src/lib/transactional-adapter-typeorm.ts
packages/transactional-adapters/transactional-adapter-typeorm/test/transactional-adapter-typeorm.spec.ts
packages/transactional/src/lib/interfaces.ts
packages/transactional/src/lib/propagation.ts
packages/transactional/src/lib/transaction-host.ts
packages/transactional/test/propagation.spec.ts
packages/transactional/test/transaction-adapter-mock.ts

This branch should be merged once the support for `Propagation.Nested` is implemented for all existing transactional adapters (that support it)
Prior work on the transactional host has been done by @gring2, as well as the implementation for the TypeORM adapter.
To add add nested transactions support for other adapters, please create a branch from this one, and also target the PR here.
---
The PR will be ready to merge once support for the following adapters is added:

feat(transactional): support nested transaction propagation
